# Hardcoded combination of all palettes
# Easy to read, safe, explicit

from .pixelit import PALETTE_LIST as PALETTES_PIXELIT, PALETTE_NAMES as PALETTE_NAMES_PIXELIT
from .image_to_pixel import PALETTE_LIST as PALETTES_IMAGE_TO_PIXEL, PALETTE_NAMES as PALETTE_NAMES_IMAGE_TO_PIXEL
from .pixelartvillage import PALETTE_LIST as PALETTES_PIXELARTVILLAGE, PALETTE_NAMES as PALETTE_NAMES_PIXELARTVILLAGE

# Combine all
PALETTE_LIST = []
PALETTE_LIST.extend(PALETTES_PIXELIT)
PALETTE_LIST.extend(PALETTES_IMAGE_TO_PIXEL)
PALETTE_LIST.extend(PALETTES_PIXELARTVILLAGE)

PALETTE_NAMES = []
PALETTE_NAMES.extend(PALETTE_NAMES_PIXELIT)
PALETTE_NAMES.extend(PALETTE_NAMES_IMAGE_TO_PIXEL)
PALETTE_NAMES.extend(PALETTE_NAMES_PIXELARTVILLAGE)
